# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Volantis
subtitle: ''
description: 'Volantis，一个高度模块化和可定制化、功能相对完善的Hexo博客主题，既可以用作个人博客，也适合用来搭建文档。'
keywords: 'Volantis,Hexo,Hexo主题,Blog,博客'
author: 'Volantis Team'
language: zh-CN
timezone: ''
avatar: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://volantis.js.org
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - manifest.json
  - start
  - CNAME
  - robots.txt
  - assets/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: false
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: '    '
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
updated_option: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis


# Deployment
## Docs: https://hexo.io/docs/deployment.html
# npm install hexo-deployer-git --save
deploy:
  - type: git
    repo: git@github.com:volantis-x/volantis-x.github.io.git
    branch: master
    message: "Github CI Auto Builder at {{ now('YYYY-MM-DD HH:mm:ss Z') }}"
# ssh-keygen -t rsa -b 4096 -C "xaoxuu@gmail.com" -N "" -f deploy_key
# 生成一对: deploy_key, deploy_key.pub，其中 deploy_key 填到源码仓库的 Secrets 的 DEPLOY_KEY 中，deploy_key.pub 填到静态文件仓库的 Deploy keys 中。

# 全局导入
import:
  meta:
    - <meta name="msapplication-TileColor" content="#ffffff">
    - <meta name="msapplication-config" content="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/browserconfig.xml">
    - <meta name="theme-color" content="#ffffff">
  link:
    - <link rel="apple-touch-icon" sizes="180x180" href="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/apple-touch-icon.png">
    - <link rel="icon" type="image/png" sizes="32x32" href="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon-32x32.png">
    - <link rel="icon" type="image/png" sizes="16x16" href="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon-16x16.png">
    - <link rel="manifest" href="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/site.webmanifest">
    - <link rel="mask-icon" href="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/safari-pinned-tab.svg" color="#5bbad5">
    - <link rel="shortcut icon" href="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon.ico">
  # script:

# https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap
sitemap:
  path: sitemap.xml
  tag: false
  category: false

# 图片懒加载
lazyload:
  enable: true
  onlypost: false
  loadingImg: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/placeholder/c617bfd2497fcea598e621413e315c368f8d8e.svg
  isSPA: true # optional

# npm install hexo-all-minifier --save
all_minifier: false

# hexo-autonofollow
nofollow:
  enable: true
  exclude:
  - xaoxuu.com
  - volantis.js.org

# autoprefixer
autoprefixer:
  exclude:
  - '*.min.css'

# offline config passed to sw-precache.
#offline:
#  maximumFileSizeToCacheInBytes: 10485760
#  staticFileGlobs:
#    - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
#  stripPrefix: public
#  verbose: true
#  runtimeCaching:
#    - urlPattern: /*
#      handler: cacheFirst
#      options:
#        origin: cdn.jsdelivr.net
#    - urlPattern: /*
#      handler: cacheFirst
#      options:
#        origin: cdnjs.cloudflare.com

marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: false
  modifyAnchors: 0
  autolink: true
  sanitizeUrl: false
  headerIds: true
  prependRoot: false
  external_link:
    enable: true
    exclude: []
    nofollow: true
