style:
  sidebar:
    effect: [shadow, floatable] # [shadow, floatable, blur]
  body:
    effect: [shadow, floatable] # [shadow, floatable, blur]
  # color:
  #   site: '#21232F' # Website background color
  #   site_inner: '#fff' # Text color inside the website background
  #   site_footer: '#fff' # Footer text color inside the website background
  #   card: '#333' # Card background color
  #   text: '#fff' # The color of the text on the card.
  #   inner: '#333' # Text color inside the button
  #   block: '#555' # Block color
  #   inlinecode: '#555' # Inline code color
  #   codeblock: '#555' # Codeblock color
  #   p: '#ccc' #

meta:
  author:
    avatar: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/avatar/avatar.png
    name: Mr. X
    url: https://xaoxuu.com
  updated:
    title: '本页文档最后更新于：'

comments:
  title: <i class='fas fa-comments'></i> 用户交流区
  subtitle: 这里仅供用户之间进行交流，有任何疑问请前往GitHub提交Issue。在评论区进行提问将不会收到开发者的任何回复！
  valine:
    appId: FIKAgh6n0pUM08JXxhJHChVQ-MdYXbMMI
    appKey: RJGiOYFc1fBvfox4frBPpRzU
    requiredFields: ['nick']
    path: /
    placeholder: 这里仅供用户之间进行交流，有任何疑问请前往GitHub提交Issue。在评论区进行提问将不会收到开发者的任何回复！

footer:
  layout: [aplayer, social, info, copyright]

plugins:
  comment_typing: false
  # backstretch:
  # #   enable: false
  #   # position: fixed
  #   images:               # For personal use only. At your own risk if used for commercial purposes !!!
  #     - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper/abstract/41F215B9-261F-48B4-80B5-4E86E165259E.jpeg
  #     # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper/abstract/BBC19066-E176-47C2-9D22-48C81EE5DF6B.jpeg
  #     # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper/abstract/B18FCBB3-67FD-48CC-B4F3-457BA145F17A.jpeg
  #     # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper/abstract/67239FBB-E15D-4F4F-8EE8-0F1C9F3C4E7C.jpeg
  #     # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper/abstract/35F12181-F0E9-45BD-B134-37E4B4A660CF.jpeg
  aplayer:
    autoplay: true
    volume: 0.4
    order: random
    # id: 4917530132 # vol red
    # id: 4917524698 # vol blue
    # id: 76244489 # vol white
    id: 5135845906 # for Volantis 3.0
  darkmodejs:
    compatible: true
