style:
  font_smoothing: true
  sidebar:
    effect: [shadow] # [shadow, floatable, blur]
  body:
    effect: [shadow] # [shadow, floatable, blur]
  color:
    text: '#333'
    p: '#333'
  #   site: '#21232F' # Website background color
  #   site_inner: '#fff' # Text color inside the website background
  #   site_footer: '#fff' # Footer text color inside the website background
  #   card: '#333' # Card background color
  #   text: '#fff' # The color of the text on the card.
  #   inner: '#333' # Text color inside the button
  #   block: '#555' # Block color
  #   inlinecode: '#555' # Inline code color
  #   codeblock: '#555' # Codeblock color
  #   p: '#ccc' #
  fontfamily:
    note-tag:
      fontfamily: 'Font Awesome 5 Pro'
meta:
  author:
    avatar: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/apple-touch-icon.png
    name: Volantis Team
    url: https://github.com/volantis-x/
  updated:
    title: '本页文档最后更新于：'

comments:
  title: #<i class='fas fa-comments'></i> 用户交流区
  subtitle: #这里仅供用户之间进行交流，有任何疑问请前往GitHub提交Issue。在评论区进行提问将不会收到开发者的任何回复！
  service: disqus
  path: /
  disqus:
    shortname: volantis

footer:
  layout: [aplayer, social, source, copyright]
  copyright: '[Copyright © 2017-2020 Volantis Team](https://github.com/volantis-x/)'

plugins:
  fontawesome: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fontawesome-pro@master/css/all.min.css
  comment_typing: false
  busuanzi: false
  backstretch:
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/016.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/019.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/025.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/033.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/052.jpg
  aplayer:
    autoplay: true
    volume: 0.4
    order: random
    # id: 4917530132 # vol red
    # id: 4917524698 # vol blue
    # id: 76244489 # vol white
    # id: 5135845906 # for Volantis 3.0
    id: 5062959861 # TOP 30
  darkmodejs:
    compatible: true
