# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Volantis
subtitle: ''
description: 'Volantis，一个高度模块化和可定制化、功能相对完善的Hexo博客主题，既可以用作个人博客，也适合用来搭建文档。'
keywords: 'Volantis,Hexo,Hexo主题,Blog,博客'
author: 'Mr. X'
language: zh-CN
timezone: ''
avatar: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/avatar/avatar.png
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://volantis.js.org
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - manifest.json
  - start
  - CNAME
  - robots.txt
  - assets/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: false
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: '    '
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis
# 覆盖主题配置
theme_config:
  style:
    sidebar:
      effect: [blur] # [shadow, floatable, blur]
    body:
      effect: [blur] # [shadow, floatable, blur]
    color:
      site_footer: '#fff'
  cover:
    search: '搜索文档'
    features:
      - name: 文档
        icon: fas fa-book
        url: /v3/getting-started/
      - name: 博文
        icon: fas fa-rss
        url: /archives/
      - name: 示例
        icon: fas fa-play-circle
        url: /examples/
      - name: 源码
        icon: fas fa-file-code
        url: https://github.com/theme-volantis/hexo-theme-volantis/
        rel: external nofollow noopener noreferrer
        target: _blank
      - name: 鸣谢
        icon: fas fa-handshake
        url: /contributors/
  meta:
    updated:
      title: '本页文档最后更新于：'
  comments:
    title: <i class='fas fa-comments'></i> 用户交流区
    subtitle: 这里仅供用户之间进行交流，有任何疑问请前往GitHub提交Issue。在评论区进行提问将不会收到开发者的任何回复！
    valine:
      appId: FIKAgh6n0pUM08JXxhJHChVQ-MdYXbMMI
      appKey: RJGiOYFc1fBvfox4frBPpRzU
      meta: [nick, mail]
      requiredFields: ['nick']
      path: /
      placeholder: 这里仅供用户之间进行交流，有任何疑问请前往GitHub提交Issue。在评论区进行提问将不会收到开发者的任何回复！
  footer:
    layout: [aplayer, social, info, copyright]
  plugins:
    comment_typing: false
    backstretch:
    #   enable: false
      position: fixed
      images:               # For personal use only. At your own risk if used for commercial purposes !!!
        - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/41F215B9-261F-48B4-80B5-4E86E165259E.jpeg
        - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/BBC19066-E176-47C2-9D22-48C81EE5DF6B.jpeg
        - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B18FCBB3-67FD-48CC-B4F3-457BA145F17A.jpeg
        - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/67239FBB-E15D-4F4F-8EE8-0F1C9F3C4E7C.jpeg
        # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/35F12181-F0E9-45BD-B134-37E4B4A660CF.jpeg
    aplayer:
      autoplay: true
      volume: 0.4
      order: random
      # id: 4917530132 # vol red
      # id: 4917524698 # vol blue
      id: 76244489 # vol white


# Deployment
## Docs: https://hexo.io/docs/deployment.html
# npm install hexo-deployer-git --save
deploy:
  - type: git
    repo: git@github.com:theme-volantis/theme-volantis.github.io.git
    branch: master
    message: "Github CI Auto Builder at {{ now('YYYY-MM-DD HH:mm:ss Z') }}"


# 全局导入
import:
  meta:
  - "<meta name='theme-color' content='#FFFFFF'>"
  link:
  - "<link rel='shortcut icon' type='image/x-icon' sizes='16x16 32x32 48x48 64x64' href='/assets/favicon/favicon.ico'>"
  - "<link rel='apple-touch-icon' type='image/png' sizes='180x180' href='/assets/favicon/favicon_180.png'>"
  - "<link rel='mask-icon' color='#1BC3FB' href='/assets/favicon/favicon_180.png'>"
  - "<link rel='manifest' href='/manifest.json'>"
  # script:

# https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap
sitemap:
  path: sitemap.xml
  tag: false
  category: false

# 图片懒加载  # hexo-lazyload-image    hexo-fs
lazyload:
  enable: true
  onlypost: false
  loadingImg: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/placeholder/c617bfd2497fcea598e621413e315c368f8d8e.svg
  isSPA: true # optional

# npm install hexo-all-minifier --save
all_minifier: false

# hexo-autonofollow
nofollow:
  enable: true
  exclude:
  - xaoxuu.com
  - volantis.js.org

# autoprefixer
autoprefixer:
  exclude:
  - '*.min.css'

# offline config passed to sw-precache.
offline:
  maximumFileSizeToCacheInBytes: 10485760
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true
  runtimeCaching:
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.jsdelivr.net
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdnjs.cloudflare.com

marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: false
  modifyAnchors: 0
  autolink: true
  sanitizeUrl: false
  headerIds: true
  prependRoot: false
  external_link:
    enable: true
    exclude: []
    nofollow: true
